### ISSUE TITLE
Discussion Thread for #815

### ISSUE THREAD

**Issue by ebonnecab** [MLH-Fellowship/httpie#1]
This is for posting Error messages and discussing which functions we decide to create.

**Comment by rch-liu** [comment]
Command: 
```
http --form POST example.com \
name="John Smith" \
cv=@document.txt
```

Error message: 
`usage: http [--json] [--form] [--compress] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--headers] [--body] [--verbose]
            [--all] [--history-print WHAT] [--stream] [--output FILE]
            [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}] [--ignore-netrc]
            [--offline] [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--max-headers MAX_HEADERS]
            [--timeout SECONDS] [--check-status] [--path-as-is]
            [--verify VERIFY] [--ssl {ssl2.3,tls1,tls1.1,tls1.2}]
            [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help]
            [--version] [--traceback] [--default-scheme DEFAULT_SCHEME]
            [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: argument REQUEST_ITEM: 'cv' is not a valid value`

This case caused by invalid argument passed to 'cv' param. Couldn't find document.txt


Command:
```
http https://po.grej
```

Error message:
```http: error: ConnectionError: HTTPSConnectionPool(host='po.grej', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10701fcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) while doing a GET request to URL: https://po.grej/```

When input an invalid address, returns cluttered error message


Command:
```
 http https://httpie.org/hello
```

Error message:
`http: error: ConnectionError: HTTPSConnectionPool(host='httpie.org', port=443): Max retries exceeded with url: /hello (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10a5f1d00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) while doing a GET request to URL: https://httpie.org/hello'

When you hit a valid address but you're offline, you get the same bad request error message.

**Comment by ebonnecab** [comment]
Command:
`http httpies.org`

Error message:
`http: error: ConnectionError: HTTPConnectionPool(host='httpies.org', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10972cc10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known')) while doing a GET request to URL: http://httpies.org/`

_This error is generated for invalid URLs. It is also generated when you connect to a good URL with no internet connection._


Command:
`http POST httpbin.org/put X-API-Token=12345 name=12345`

Error message:
`HTTP/1.1 405 METHOD NOT ALLOWED
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Allow: PUT, OPTIONS
Connection: keep-alive
Content-Length: 178
Content-Type: text/html
Date: Wed, 10 Jun 2020 01:34:00 GMT
Server: gunicorn/19.9.0

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
405 Method Not Allowed
Method Not Allowed
The method is not allowed for the requested URL.`

_This error is generated from using the wrong method with URL type._


Command:
` http /foo`

Error:
`http: error: InvalidURL: Invalid URL 'http:///foo': No host supplied`

_This error is generated when I defined a localhost shortcut without the colon. See [here](https://httpie.org/docs#url-shortcuts-for-localhost) in documentation._

edot@Ebonnes-MacBook-Air dev % http --donload httpbin.org/image/png     

usage: http [--json] [--form] [--compress] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--headers] [--body] [--verbose]
            [--all] [--history-print WHAT] [--stream] [--output FILE]
            [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}] [--ignore-netrc]
            [--offline] [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--max-headers MAX_HEADERS]
            [--timeout SECONDS] [--check-status] [--path-as-is]
            [--verify VERIFY] [--ssl {ssl2.3,tls1,tls1.1,tls1.2}]
            [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help]
            [--version] [--traceback] [--default-scheme DEFAULT_SCHEME]
            [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: unrecognized arguments: --donload`

_This error was generated from using an invalid argument. I believe these types of errors are handled using their argparser class but we can confirm whether they want us to leave this error message as is._


Command:
`http -a usernameA:passworda httpbin.org/basic-auth/username/password`

Error:
`HTTP/1.1 401 UNAUTHORIZED
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 0
Date: Wed, 10 Jun 2020 18:22:33 GMT
Server: gunicorn/19.9.0
WWW-Authenticate: Basic realm="Fake Realm"`

_This error is generated when providing the wrong username and password to basic auth_
